const data= [
    {
        "id": 1,
        "first_name": "Duff",
        "last_name": "MacTeggart",
        "email": "dmacteggart0@mozilla.com",
        "gender": "Male",
        "country": "Indonesia",
        "avatar": "https://robohash.org/temporaetin.png?size=50x50&set=set1"
      }, {
        "id": 2,
        "first_name": "Tripp",
        "last_name": "Lupton",
        "email": "tlupton1@topsy.com",
        "gender": "Male",
        "country": "Poland",
        "avatar": "https://robohash.org/utnecessitatibusest.png?size=50x50&set=set1"
      }, {
        "id": 3,
        "first_name": "Dew",
        "last_name": "Franzke",
        "email": "dfranzke2@noaa.gov",
        "gender": "Male",
        "country": "Peru",
        "avatar": "https://robohash.org/voluptasexpeditaquibusdam.bmp?size=50x50&set=set1"
      }, {
        "id": 4,
        "first_name": "Terrel",
        "last_name": "Barbe",
        "email": "tbarbe3@drupal.org",
        "gender": "Male",
        "country": "Serbia",
        "avatar": "https://robohash.org/quibusdamillumlaborum.jpg?size=50x50&set=set1"
      }, {
        "id": 5,
        "first_name": "Beatriz",
        "last_name": "Snape",
        "email": "bsnape4@buzzfeed.com",
        "gender": "Female",
        "country": "Philippines",
        "avatar": "https://robohash.org/adetab.jpg?size=50x50&set=set1"
      }, {
        "id": 6,
        "first_name": "Bill",
        "last_name": "Hinsche",
        "email": "bhinsche5@blogger.com",
        "gender": "Male",
        "country": "Mongolia",
        "avatar": "https://robohash.org/utquopariatur.png?size=50x50&set=set1"
      }, {
        "id": 7,
        "first_name": "Rodolfo",
        "last_name": "Feaveer",
        "email": "rfeaveer6@comsenz.com",
        "gender": "Male",
        "country": "Cameroon",
        "avatar": "https://robohash.org/ametnobisvoluptatem.bmp?size=50x50&set=set1"
      }, {
        "id": 8,
        "first_name": "Dehlia",
        "last_name": "Posnett",
        "email": "dposnett7@nytimes.com",
        "gender": "Female",
        "country": "Philippines",
        "avatar": "https://robohash.org/deseruntconsecteturunde.bmp?size=50x50&set=set1"
      }, {
        "id": 9,
        "first_name": "Jaine",
        "last_name": "Degg",
        "email": "jdegg8@amazon.co.uk",
        "gender": "Female",
        "country": "Indonesia",
        "avatar": "https://robohash.org/optioconsequaturet.png?size=50x50&set=set1"
      }, {
        "id": 10,
        "first_name": "Nollie",
        "last_name": "Dunstall",
        "email": "ndunstall9@homestead.com",
        "gender": "Female",
        "country": "Indonesia",
        "avatar": "https://robohash.org/doloresrerumaliquid.png?size=50x50&set=set1"
      }];

      export default data;